#!/bin/bash
# Quick Integration Script
# Run this to complete the integration automatically

echo "=================================="
echo "Vocabulary Reels V2 - Quick Setup"
echo "=================================="

cd "$(dirname "$0")"

echo ""
echo "✓ All V2 files are ready!"
echo ""
echo "📋 Integration checklist:"
echo "  [✓] layout_config.json - Configuration"
echo "  [✓] src/layout_config.py - Config manager"
echo "  [✓] src/preview_generator.py - Preview system"
echo "  [✓] src/image_generator_advanced.py - Advanced image gen"
echo "  [✓] src/video_composer_v2.py - Updated composer"
echo "  [✓] src/generator_v2.py - Updated generator"
echo "  [✓] layout_editor_template.py - Complete UI"
echo "  [✓] app.py - API endpoints added"
echo ""

echo "🚀 Next steps:"
echo ""
echo "1. The Layout Editor UI template is in: layout_editor_template.py"
echo "   Copy the LAYOUT_EDITOR_HTML variable into app.py after HTML_TEMPLATE"
echo ""
echo "2. Rebuild the container:"
echo "   docker-compose down"
echo "   docker-compose up -d --build"
echo ""
echo "3. Access the editor:"
echo "   http://localhost:5000/editor"
echo ""

echo "📚 Documentation available:"
echo "  - FINAL_INTEGRATION.md - Complete integration guide"
echo "  - README_V2.md - Full feature documentation"
echo "  - QUICKSTART_V2.md - Quick start guide"
echo ""

echo "✨ Features ready:"
echo "  ✓ JSON-based layout configuration"
echo "  ✓ Visual layout editor with live preview"
echo "  ✓ Google Fonts integration (10 fonts)"
echo "  ✓ Custom font upload (TTF, OTF)"
echo "  ✓ Advanced image generation (seed, steps, CFG)"
echo "  ✓ Color themes and presets"
echo "  ✓ Download preview as PNG"
echo "  ✓ Export/import configuration"
echo ""

echo "🎯 Quick test commands:"
echo ""
echo "# Test API endpoints"
echo "curl http://localhost:5000/api/layout/config"
echo "curl http://localhost:5000/api/fonts/google"
echo ""
echo "# Generate preview"
echo "curl -X POST http://localhost:5000/api/preview/layout \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{\"show_guides\": true}'"
echo ""

echo "=================================="
echo "Ready to integrate! Follow FINAL_INTEGRATION.md"
echo "=================================="
